name: dev
variables:
  - name: baseUrl
    value: https://hywnn45imhk25aqtgjbdopdhii0xhkej.lambda-url.us-west-2.on.aws
  - name: test_user_name
    value: Ayato Hardy
  - name: test_email
    value: ayatomac@icloud.com
  - name: test_first_language
    value: ja
  - name: test_target_language
    value: ko
  - name: test_password
    value: password123
