ALTER TABLE public.notebooks ADD COLUMN synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.notes ADD COLUMN synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.quiz_runs ADD COLUMN synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
